### ISSUE TITLE
Error during setup of component toon

### ISSUE THREAD

**Issue by PostSven** [krocat/ToonHA#35]
I am getting the following error since yesterday:

Running the latest Hass version (Docker image) and the latest toon custom component.

```
Log Details (ERROR)

Wed Apr 18 2018 06:58:58 GMT+0200 (W. Europe Daylight Time)

Error during setup of component toon

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 145, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/toon.py", line 70, in setup
    config['toon'][CONF_NAME])
  File "/config/custom_components/toon.py", line 116, in __init__
    self.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 319, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/toon.py", line 123, in update
    self.data['power_current'] = self.toon.power.value
  File "/config/deps/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 322, in power
    power = self.status['powerUsage']
KeyError: 'powerUsage'
```

**Comment by PostSven** [comment]
Just to add some more to this, i have tried to print the (toon.power.value) locally using the toonapilib and i get this error:

```
C:\Users\spost\Desktop>python toontest.py
Traceback (most recent call last):
  File "toontest.py", line 10, in <module>
    print(toon.power.value)
  File "C:\Users\spost\AppData\Local\Programs\Python\Python36\lib\site-packages\toonapilib\toonapilib.py", line 322, in power
    power = self.status['powerUsage']
KeyError: 'powerUsage'

```

**Comment by Housebeer** [comment]
I'm having this issue as well after upgrading to Home Assistant 67.0

**Comment by scheric** [comment]
I am getting this problem too.
Could you try to recover from a backup to see if it is the Home Assistant update or if it is something else?
It could be toon changing something in their servers if you look at this https://github.com/costastf/toonapilib/issues/7

**Comment by wtrdk** [comment]
I use toonapilib from costastf without Home Assistant, and I experience the same issue, so it's not Home Assistant's fault ;-)
