### ISSUE TITLE
Error during setup of component toon

### ISSUE THREAD

**Issue by exqua** [krocat/ToonHA#44]
I all, 

I get the following error when i want to use toon in Home Assistent.
Can someone help me out with this?

**********************************************************************************
Error during setup of component toon
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 319, in _get_status_value
    output = self.status[value]
KeyError: 'powerUsage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/toon.py", line 70, in setup
    config['toon'][CONF_NAME])
  File "/config/custom_components/toon.py", line 116, in __init__
    self.update()
  File "/usr/src/app/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/toon.py", line 123, in update
    self.data['power_current'] = self.toon.power.value
  File "/config/deps/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 339, in power
    power = self._get_status_value('powerUsage')
  File "/config/deps/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 321, in _get_status_value
    raise IncompleteStatus(self.status)
toonapilib.toonapilibexceptions.IncompleteStatus: {'code': 500, 'message': 'Internal Server Error', 'description': 'Error communicating with Toon'}

**Comment by scheric** [comment]
Hi, As you can see in the last line: {'code': 500, 'message': 'Internal Server Error', 'description': 'Error communicating with Toon'}

problem:

The toon servers aren't so strong. They regularly fail.

solution:

Reboot home assistant and check for errors

**Comment by exqua** [comment]
Hi Scheric,
Thanks for your input.

I've reboot like 20 times in the last 2 days.
Are there other options i can try?

Thanks.

**Comment by costastf** [comment]
you can try rebooting toon itself, it has been known to fix issues.

**Comment by scheric** [comment]
If it does not work after an reaboot from toon. You could try the official TOON  Android / iOS app.

**Comment by exqua** [comment]
> 
> 
> If it does not work after an reaboot from toon. You could try the official TOON Android / iOS app.

Hi, The official app does work perfectly so i think i made a mistake. but i can't find it.

**Comment by scheric** [comment]
Check the API key from the developer website. Or create an new API key.

**Comment by costastf** [comment]
I am guessing this was an issue with the service. If @exqua  you still have issues please reopen.
