### ISSUE TITLE
Beta Home Assistant 0.89.0b2 - policies.ratelimit.QuotaViolation

### ISSUE THREAD

**Issue by rikmaris** [krocat/ToonHA#50]
After installing the BETA of Hass, connecting with toon. I get this issue:
(i removed my personals)

Strange one: i connect to toon with @hotmail.com e-mailadress. And in this log file is my @gmail.com emailadres.. i don't get it..

Error setting up entry eneco-001-xxxx for toon
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 175, in _get_agreements
    for agreement in agreements]
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 175, in <listcomp>
    for agreement in agreements]
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 283, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/toon/__init__.py", line 56, in async_setup_entry
    display_common_name=entry.data[CONF_DISPLAY]))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 106, in __init__
    self._authenticate()
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 153, in _authenticate
    self._get_agreements()
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 178, in _get_agreements
    raise AgreementsRetrievalError(response.text)
toonapilib.toonapilibexceptions.AgreementsRetrievalError: {"fault":{"faultstring":"Rate limit quota violation. Quota limit  exceeded. Identifier : xxx@gmail.com","detail":{"errorcode":"policies.ratelimit.QuotaViolation"}}}

**Comment by costastf** [comment]
As you can see from the last message, you are in quota violation with the service. Not sure how you get that, never happened to me. As for the email issue, that is indeed strange. Can you please try the library out of home assistant context and report back?

**Comment by scheric** [comment]
there is a hidden folder in you configure folder. In that folder is  a file that is called config_entries. (Mary something like that)
The data stored in that place is used for the integrated home assistant component
![config](https://user-images.githubusercontent.com/38077357/53912792-006eb380-405a-11e9-8a92-bf30da42dca4.PNG)

You can always add this component to test the API. (instructions are in the readme)

**Comment by rikmaris** [comment]
> Can you please try the library out of home assistant context and report back?

How does it works? I don't know what to do

**Comment by costastf** [comment]
You can follow installation instructions and usage from https://toonapilib.readthedocs.io/en/latest

**Comment by rikmaris** [comment]
> there is a hidden folder in you configure folder. In that folder is a file that is called config_entries. (Mary something like that)
> The data stored in that place is used for this component.
> ![config](https://user-images.githubusercontent.com/38077357/53912792-006eb380-405a-11e9-8a92-bf30da42dca4.PNG)

In this file is the right username (@hotmail.com) what i use to log on to my toon/mijn eneco.

**Comment by scheric** [comment]
do you have some leftovers in your configuration.yaml
only this is needed. for the reworked component

```yaml
toon:
    consumer_key: API_CONSUMER_KEY
    consumer_secret: API_CONSUMER_SECRET
```

**Comment by rikmaris** [comment]
1. I have no leftovers of the custom component
2. After a restart of Hass it works. Very nice. But after 1,5 hours the issue is back again. 
I did restart Hass at 8:11 AM this morning. And at 09:52 AM the first error occured.

deps/lib/python3.7/site-packages/toonapilib/toonapilib.py (ERROR) - message first occured at 09:52 and shows up 46 times

**Comment by scheric** [comment]
Do you have any other components that use an email address for authentication.

**Comment by rikmaris** [comment]
it looks like my account for https://developer.toon.eu/ is the problem. That's one is in use for this. All other auth by e-mailadress has an sepparated account.

So the component polls to many with the account https://developer.toon.eu/. Because is works for 1,5 hour. So my settings are good. But after that time period it's blocked..

**Comment by rikmaris** [comment]
I have some more errors (not only quota violation); i will post them below

1:
pdate for sensor.current_power_usage fails
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 351, in _get_status_value
    output = self.status[value]
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/toon/sensor.py", line 139, in update
    section = getattr(self.toon, self.section)
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 371, in power
    power = self._get_status_value('powerUsage')
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 353, in _get_status_value
    raise IncompleteStatus(self.status)
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)
-----
2.
Thu Mar 07 2019 16:46:37 GMT+0100 (Midden-Europese standaardtijd)
Update for sensor.solar_production_to_grid fails
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 351, in _get_status_value
    output = self.status[value]
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/toon/sensor.py", line 139, in update
    section = getattr(self.toon, self.section)
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 385, in solar
    power = self._get_status_value('powerUsage')
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 353, in _get_status_value
    raise IncompleteStatus(self.status)
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)
-------
3.
Thu Mar 07 2019 16:46:32 GMT+0100 (Midden-Europese standaardtijd)
Update for sensor.power_cost_today fails
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 351, in _get_status_value
    output = self.status[value]
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/toon/sensor.py", line 139, in update
    section = getattr(self.toon, self.section)
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 371, in power
    power = self._get_status_value('powerUsage')
  File "/config/deps/lib/python3.7/site-packages/toonapilib/toonapilib.py", line 353, in _get_status_value
    raise IncompleteStatus(self.status)
  File "/config/deps/lib/python3.7/site-packages/cachetools/__init__.py", line 48, in wrapper
    cache[k] = v
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 94, in __setitem__
    self.expire(time)
  File "/config/deps/lib/python3.7/site-packages/cachetools/ttl.py", line 174, in expire
    cache_delitem(self, curr.key)
  File "/config/deps/lib/python3.7/site-packages/cachetools/cache.py", line 63, in __delitem__
    del self.__data[key]
KeyError: (<toonapilib.toonapilib.Toon object at 0x71f9f2f0>,)

**Comment by scheric** [comment]
@rikmaris are you now using HA: 0.89 or still using a beta version. 
I can not reproduce these issues.

***
My https://developer.toon.eu/ account is different than my Eneco account. the API does not give any email address. these errors are really weird

**Comment by costastf** [comment]
@rikmaris can you please try out the library as mentioned in the documentation I specified and report back please?

**Comment by yellowonblack** [comment]
For the last 5-6 months I used ToonHA custom component and today  I updated to 0.89.1 and tried to use the built-in new Toon component, but after few hours I started to get QuotaViolation error.
Rolling back to ToonHA custom component and everything seems back to normal.

**Comment by costastf** [comment]
I guess you should open an issue on the official component

**Comment by yellowonblack** [comment]
The same problem on HA  [https://github.com/home-assistant/home-assistant/issues/21825](url)

**Comment by yellowonblack** [comment]
> I guess you should open an issue on the official component

This has been done already. 

As for the actual ToonHA custom component, it works perfect for my needs.
Thanks to all the contributors.

**Comment by rikmaris** [comment]
You can close this issue. 
i did remove my integration with Nest and the error didn't occur anymore. Only have the same problem as @yellowonblack . So i will use the custom component.
