### ISSUE TITLE
Home assistant fails to load toon.climate

### ISSUE THREAD

**Issue by michelmolleman** [krocat/ToonHA#51]
First of all, great work. all sensors are working as expected except the thermostat. I get the following error with home assistant 0.89:

Error loading custom_components.toon.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/toon/climate.py", line 9, in <module>
    from homeassistant.components.climate import (ClimateDevice,
ImportError: cannot import name 'STATE_AUTO' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)

**Comment by scheric** [comment]
The climate constants have bin moved in HA home-assistant/home-assistant#20945
I am working on a fix.

**Comment by scheric** [comment]
Can you try the new master?

**Comment by michelmolleman** [comment]
Works like a charm again. Thanks a lot... keep up the good work!
